/* Generated by JTB 1.4.7 */
package com.lopiter.parser.node;

import com.lopiter.parser.visitor.*;

public class MyParserifStatemet implements INode {

  public NodeToken f0;

  public NodeChoice f1;

  public NodeChoice f2;

  public NodeChoice f3;

  public NodeToken f4;

  public MyParserstatement f5;

  public NodeToken f6;

  private static final long serialVersionUID = 147L;

  public MyParserifStatemet(final NodeToken n0, final NodeChoice n1, final NodeChoice n2, final NodeChoice n3, final NodeToken n4, final MyParserstatement n5, final NodeToken n6) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
