/* Generated by JTB 1.4.7 */
package visitor;

import syntaxtree.*;

public interface IRetArguVisitor<R, A> {

  public R visit(final NodeChoice n, final A argu);

  public R visit(final NodeList n, final A argu);

  public R visit(final NodeListOptional n, final A argu);

  public R visit(final NodeOptional n, final A argu);

  public R visit(final NodeSequence n, final A argu);

  public R visit(final NodeTCF n, final A argu);

  public R visit(final NodeToken n, final A argu);

  public R visit(final compilationunit n, final A argu);

  public R visit(final function n, final A argu);

  public R visit(final statement n, final A argu);

  public R visit(final forStatement n, final A argu);

  public R visit(final printStatement n, final A argu);

  public R visit(final ifStatemet n, final A argu);

  public R visit(final readStatement n, final A argu);

  public R visit(final callStatement n, final A argu);

  public R visit(final setValueStatement n, final A argu);

}
