/* Generated by JTB 1.4.7 */
package visitor;

import syntaxtree.*;

public interface IRetVisitor<R> {

  public R visit(final NodeChoice n);

  public R visit(final NodeList n);

  public R visit(final NodeListOptional n);

  public R visit(final NodeOptional n);

  public R visit(final NodeSequence n);

  public R visit(final NodeTCF n);

  public R visit(final NodeToken n);

  public R visit(final compilationunit n);

  public R visit(final function n);

  public R visit(final statement n);

  public R visit(final forStatement n);

  public R visit(final printStatement n);

  public R visit(final ifStatemet n);

  public R visit(final readStatement n);

  public R visit(final callStatement n);

  public R visit(final setValueStatement n);

}
