/* Generated by JTB 1.4.7 */
package visitor;

import syntaxtree.*;

public interface IVoidVisitor {

  public void visit(final NodeChoice n);

  public void visit(final NodeList n);

  public void visit(final NodeListOptional n);

  public void visit(final NodeOptional n);

  public void visit(final NodeSequence n);

  public void visit(final NodeTCF n);

  public void visit(final NodeToken n);

  public void visit(final compilationunit n);

  public void visit(final function n);

  public void visit(final statement n);

  public void visit(final forStatement n);

  public void visit(final printStatement n);

  public void visit(final ifStatemet n);

  public void visit(final readStatement n);

  public void visit(final callStatement n);

  public void visit(final setValueStatement n);

}
