/* Generated by JTB 1.4.7 */
package visitor;

import syntaxtree.*;

public interface IVoidArguVisitor<A> {

  public void visit(final NodeChoice n, final A argu);

  public void visit(final NodeList n, final A argu);

  public void visit(final NodeListOptional n, final A argu);

  public void visit(final NodeOptional n, final A argu);

  public void visit(final NodeSequence n, final A argu);

  public void visit(final NodeTCF n, final A argu);

  public void visit(final NodeToken n, final A argu);

  public void visit(final compilationunit n, final A argu);

  public void visit(final function n, final A argu);

  public void visit(final statement n, final A argu);

  public void visit(final forStatement n, final A argu);

  public void visit(final printStatement n, final A argu);

  public void visit(final ifStatemet n, final A argu);

  public void visit(final readStatement n, final A argu);

  public void visit(final callStatement n, final A argu);

  public void visit(final setValueStatement n, final A argu);

}
