/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */
package com.lopiter.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FUNCTION = 3;
  /** RegularExpression Id. */
  int FOR = 4;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int NULL = 6;
  /** RegularExpression Id. */
  int PRINT = 7;
  /** RegularExpression Id. */
  int READ = 8;
  /** RegularExpression Id. */
  int TO = 9;
  /** RegularExpression Id. */
  int LEFT_BRACE = 10;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 11;
  /** RegularExpression Id. */
  int LEFT_PARENTHESIS = 12;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESIS = 13;
  /** RegularExpression Id. */
  int COMMA_CHAR = 14;
  /** RegularExpression Id. */
  int IF_EQUAL = 15;
  /** RegularExpression Id. */
  int IF_NOT_EQUAL = 16;
  /** RegularExpression Id. */
  int INTEGER = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int IDENTIFIER = 19;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 20;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 21;
  /** RegularExpression Id. */
  int LETTER = 22;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\"FUNCTION\"",
    "\"FOR\"",
    "\"IF\"",
    "\"NULL\"",
    "\"PRINT\"",
    "\"READ\"",
    "\"TO\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"==\"",
    "\"!=\"",
    "<INTEGER>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<CHAR_LITERAL>",
    "<QUOTED_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
  };

}
