/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */
package com.lopiter.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 3;
  /** RegularExpression Id. */
  int LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int FUNCTION = 5;
  /** RegularExpression Id. */
  int FOR = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int NULL = 8;
  /** RegularExpression Id. */
  int PRINT = 9;
  /** RegularExpression Id. */
  int READ = 10;
  /** RegularExpression Id. */
  int TO = 11;
  /** RegularExpression Id. */
  int VAR = 12;
  /** RegularExpression Id. */
  int LEFT_BRACE = 13;
  /** RegularExpression Id. */
  int RIGHT_BRACE = 14;
  /** RegularExpression Id. */
  int LEFT_PARENTHESIS = 15;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESIS = 16;
  /** RegularExpression Id. */
  int COMMA_CHAR = 17;
  /** RegularExpression Id. */
  int EQUAL = 18;
  /** RegularExpression Id. */
  int IF_EQUAL = 19;
  /** RegularExpression Id. */
  int IF_NOT_EQUAL = 20;
  /** RegularExpression Id. */
  int INTEGER = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;
  /** RegularExpression Id. */
  int IDENTIFIER = 23;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 24;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 25;
  /** RegularExpression Id. */
  int LETTER = 26;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<MULTI_LINE_COMMENT>",
    "<LINE_COMMENT>",
    "\"FUNCTION\"",
    "\"FOR\"",
    "\"IF\"",
    "\"NULL\"",
    "\"PRINT\"",
    "\"READ\"",
    "\"TO\"",
    "\"VAR\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "<INTEGER>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<CHAR_LITERAL>",
    "<QUOTED_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
  };

}
