/* Generated by JTB 1.4.7 */
package syntaxtree;

import visitor.*;

public class setValueStatement implements INode {

  public NodeToken f0;

  public NodeToken f1;

  public NodeOptional f2;

  private static final long serialVersionUID = 147L;

  public setValueStatement(final NodeToken n0, final NodeToken n1, final NodeOptional n2) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
