/* Generated by JTB 1.4.7 */
package com.lopiter.parser.visitor;

import com.lopiter.parser.node.*;
import java.util.*;

public class DepthFirstVoidArguVisitor<A> implements IVoidArguVisitor<A> {


  public void visit(final NodeChoice n, final A argu) {
    n.choice.accept(this, argu);
    return;
  }

  public void visit(final NodeList n, final A argu) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this, argu);
    }
    return;
  }

  public void visit(final NodeListOptional n, final A argu) {
    if (n.present()) {
      for (final Iterator<INode> e = n.elements(); e.hasNext();) {
        e.next().accept(this, argu);
        }
      return;
    } else
      return;
  }

  public void visit(final NodeOptional n, final A argu) {
    if (n.present()) {
      n.node.accept(this, argu);
      return;
    } else
      return;
  }

  public void visit(final NodeSequence n, final A argu) {
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      e.next().accept(this, argu);
    }
    return;
  }

  public void visit(final NodeTCF n, final A argu) {
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return;
  }

  public void visit(final NodeToken n, final A argu) {
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return;
  }

  public void visit(final MyParsercompilationunit n, final A argu) {
    // f0 -> ( function() )+
    n.f0.accept(this, argu);
  }

  public void visit(final MyParserfunction n, final A argu) {
    // f0 -> <FUNCTION>
    n.f0.accept(this, argu);
    // f1 -> <IDENTIFIER>
    n.f1.accept(this, argu);
    // f2 -> <LEFT_PARENTHESIS>
    n.f2.accept(this, argu);
    // f3 -> [ <IDENTIFIER> ]
    n.f3.accept(this, argu);
    // f4 -> ( #0 <COMMA_CHAR> #1 <IDENTIFIER> )*
    n.f4.accept(this, argu);
    // f5 -> <RIGHT_PARENTHESIS>
    n.f5.accept(this, argu);
    // f6 -> <LEFT_BRACE>
    n.f6.accept(this, argu);
    // f7 -> [ statement() ]
    n.f7.accept(this, argu);
    // f8 -> <RIGHT_BRACE>
    n.f8.accept(this, argu);
  }

  public void visit(final MyParserstatement n, final A argu) {
    // f0 -> ( %0 printStatement()
    // .. .. | %1 forStatement()
    // .. .. | %2 ifStatemet()
    // .. .. | %3 readStatement()
    // .. .. | %4 callStatement()
    // .. .. | %5 setValueStatement() )+
    n.f0.accept(this, argu);
  }

  public void visit(final MyParserforStatement n, final A argu) {
    // f0 -> <FOR>
    n.f0.accept(this, argu);
    // f1 -> <INTEGER>
    n.f1.accept(this, argu);
    // f2 -> <TO>
    n.f2.accept(this, argu);
    // f3 -> <INTEGER>
    n.f3.accept(this, argu);
    // f4 -> <LEFT_BRACE>
    n.f4.accept(this, argu);
    // f5 -> statement()
    n.f5.accept(this, argu);
    // f6 -> <RIGHT_BRACE>
    n.f6.accept(this, argu);
  }

  public void visit(final MyParserprintStatement n, final A argu) {
    // f0 -> <PRINT>
    n.f0.accept(this, argu);
    // f1 -> ( %0 <IDENTIFIER>
    // .. .. | %1 <QUOTED_IDENTIFIER> )
    n.f1.accept(this, argu);
  }

  public void visit(final MyParserifStatemet n, final A argu) {
    // f0 -> <IF>
    n.f0.accept(this, argu);
    // f1 -> ( %0 <IDENTIFIER>
    // .. .. | %1 <NULL> )
    n.f1.accept(this, argu);
    // f2 -> ( %0 <IF_EQUAL>
    // .. .. | %1 <IF_NOT_EQUAL> )
    n.f2.accept(this, argu);
    // f3 -> ( %0 <IDENTIFIER>
    // .. .. | %1 <NULL> )
    n.f3.accept(this, argu);
    // f4 -> <LEFT_BRACE>
    n.f4.accept(this, argu);
    // f5 -> statement()
    n.f5.accept(this, argu);
    // f6 -> <RIGHT_BRACE>
    n.f6.accept(this, argu);
  }

  public void visit(final MyParserreadStatement n, final A argu) {
    // f0 -> <READ>
    n.f0.accept(this, argu);
    // f1 -> <QUOTED_IDENTIFIER>
    n.f1.accept(this, argu);
    // f2 -> <TO>
    n.f2.accept(this, argu);
    // f3 -> <IDENTIFIER>
    n.f3.accept(this, argu);
  }

  public void visit(final MyParsercallStatement n, final A argu) {
    // f0 -> <IDENTIFIER>
    n.f0.accept(this, argu);
    // f1 -> <LEFT_PARENTHESIS>
    n.f1.accept(this, argu);
    // f2 -> [ <IDENTIFIER> ]
    n.f2.accept(this, argu);
    // f3 -> ( #0 <COMMA_CHAR> #1 <IDENTIFIER> )*
    n.f3.accept(this, argu);
    // f4 -> <RIGHT_PARENTHESIS>
    n.f4.accept(this, argu);
  }

  public void visit(final MyParsersetValueStatement n, final A argu) {
    // f0 -> <VAR>
    n.f0.accept(this, argu);
    // f1 -> <IDENTIFIER>
    n.f1.accept(this, argu);
    // f2 -> [ #0 <EQUAL>
    // .. .. . #1 ( %0 <IDENTIFIER>
    // .. .. . .. | %1 <QUOTED_IDENTIFIER>
    // .. .. . .. | %2 <INTEGER> ) ]
    n.f2.accept(this, argu);
  }

}
