/* Generated by JTB 1.4.7 */
package com.lopiter.parser.visitor;

import com.lopiter.parser.node.*;

public interface IRetVisitor<R> {

  public R visit(final NodeChoice n);

  public R visit(final NodeList n);

  public R visit(final NodeListOptional n);

  public R visit(final NodeOptional n);

  public R visit(final NodeSequence n);

  public R visit(final NodeTCF n);

  public R visit(final NodeToken n);

  public R visit(final MyParsercompilationunit n);

  public R visit(final MyParserfunction n);

  public R visit(final MyParserstatement n);

  public R visit(final MyParserforStatement n);

  public R visit(final MyParserprintStatement n);

  public R visit(final MyParserifStatemet n);

  public R visit(final MyParserreadStatement n);

  public R visit(final MyParsercallStatement n);

  public R visit(final MyParsersetValueStatement n);

}
