/* Generated by JTB 1.4.7 */
package com.lopiter.parser.visitor;

import com.lopiter.parser.node.*;

public interface IRetArguVisitor<R, A> {

  public R visit(final NodeChoice n, final A argu);

  public R visit(final NodeList n, final A argu);

  public R visit(final NodeListOptional n, final A argu);

  public R visit(final NodeOptional n, final A argu);

  public R visit(final NodeSequence n, final A argu);

  public R visit(final NodeTCF n, final A argu);

  public R visit(final NodeToken n, final A argu);

  public R visit(final MyParsercompilationunit n, final A argu);

  public R visit(final MyParserfunction n, final A argu);

  public R visit(final MyParserstatement n, final A argu);

  public R visit(final MyParserforStatement n, final A argu);

  public R visit(final MyParserprintStatement n, final A argu);

  public R visit(final MyParserifStatemet n, final A argu);

  public R visit(final MyParserreadStatement n, final A argu);

  public R visit(final MyParsercallStatement n, final A argu);

  public R visit(final MyParsersetValueStatement n, final A argu);

}
