/* Generated by JTB 1.4.7 */
package com.lopiter.parser.visitor;

import com.lopiter.parser.node.*;

public interface IVoidVisitor {

  public void visit(final NodeChoice n);

  public void visit(final NodeList n);

  public void visit(final NodeListOptional n);

  public void visit(final NodeOptional n);

  public void visit(final NodeSequence n);

  public void visit(final NodeTCF n);

  public void visit(final NodeToken n);

  public void visit(final MyParsercompilationunit n);

  public void visit(final MyParserfunction n);

  public void visit(final MyParserstatement n);

  public void visit(final MyParserforStatement n);

  public void visit(final MyParserprintStatement n);

  public void visit(final MyParserifStatemet n);

  public void visit(final MyParserreadStatement n);

  public void visit(final MyParsercallStatement n);

  public void visit(final MyParsersetValueStatement n);

}
